// layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { PublicHeader } from "./components/public-header";
import { SessionProvider } from "next-auth/react"; // Import SessionProvider
import DbConnect from "@/utils/dbConnect";
import User from "@/models/User";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  DbConnect();
  let session = await auth();

  if (session) {
    if (session.user) {
      let user = await User.findOne({ email: session.user.email })

      if (!user) {
        let user = await User.create({ name: session.user.name, email: session.user.email });

      }

    }
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider> {/* Wrap with SessionProvider */}
          <PublicHeader />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
